version: '3'
services:

  webserver:
    build: ./app/
    # ports:
    #   - "12345:80"
    depends_on:
      - dbserver
    networks:
      - net_db

  dbserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    networks:
      - net_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      # SA_PASSWORD: "XXXX"
    volumes:
      - "./volumes/dbserver:/var/opt"

networks:
  net_db:
    driver: bridge
    internal: true
